//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TogetherNotes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class artist_genres
    {
        public int artist_id { get; set; }
        public int genre_id { get; set; }
        public Nullable<System.DateTime> creation_date { get; set; }
    
        public virtual artists artists { get; set; }
        public virtual genres genres { get; set; }
    }
}
