//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TogetherNotes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class contracts
    {
        public int artist_id { get; set; }
        public int space_id { get; set; }
        public string meet_type { get; set; }
        public System.DateTimeOffset init_hour { get; set; }
        public System.DateTimeOffset end_hour { get; set; }
    
        public virtual app app { get; set; }
        public virtual app app1 { get; set; }
    }
}
